# Generated by Django 5.0.1 on 2024-01-14 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('img1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('img2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('img3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('img4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('img5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('coursedep', models.ManyToManyField(to='core.coursedep')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('experience', models.SmallIntegerField(default=0)),
                ('education', models.CharField(max_length=255)),
                ('hobbies', models.ManyToManyField(to='core.hobbies')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.lessons')),
            ],
        ),
    ]
