# Generated by Django 5.0.1 on 2024-01-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coursedep_img_lessons_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
