# Generated by Django 5.0.1 on 2024-01-15 18:33

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teachers_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='Name', verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedep',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessons',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 1, 15, 18, 33, 12, 376077, tzinfo=datetime.timezone.utc), verbose_name='url'),
            preserve_default=False,
        ),
    ]
